
name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */24 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - name: Generate
        uses: Platane/snk@main
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./assets/github-contribution-grid-snake.gif
            ./assets/github-contribution-grid-snake.svg
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
